server:
  servlet:
    context-path: "/api"

spring:
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
  datasource:
    url: jdbc:postgresql://localhost:5432/lyukina_fashion_store
    username: postgres
    driver-class-name: org.postgresql.Driver
    password: postgres

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


data-store:
  path: "D:\\pic_store"

security:
  admin:
    login: admin
    password: admin

products:
  items-on-page: 6

logging:
  level:
    ROOT: info
