server:
  servlet:
    context-path: "/api"

spring:
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
  datasource:
    url:
    username:
    driver-class-name: org.postgresql.Driver
    password:

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

  jpa:
    hibernate:
      ddl-auto: validate

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


data-store:
  path:

security:
  admin:
    login:
    password:

products:
  items-on-page: 6

logging:
  level:
    ROOT: info

notification:
  email-from:
